bla

diff --git a/.github/workflows/os_test.yml b/.github/workflows/os_test.yml
--- a/.github/workflows/os_test.yml
+++ b/.github/workflows/os_test.yml
@@ -51,21 +51,19 @@ jobs:
         export CC="/usr/bin/gcc"
         pip install . -v
         module_file=$(find gbrl/ -name "*.so")
-        install_name_tool -change /opt/homebrew/opt/libomp/lib/libomp.dylib @loader_path/include/libomp/libomp.dylib $module_file
+        install_name_tool -change /opt/homebrew/opt/libomp/lib/libomp.dylib @loader_path/../include/libomp/libomp.dylib $module_file
+    
     - name: Install Python dependencies and build the project windows
       if: matrix.os == 'windows-latest'
       run: |
         python -m pip install --upgrade pip
         pip install . -v
 
-    - name: Check linked libraries
+    - name: Check linked libraries Mac
+      if: matrix.os == 'macos-latest'
       run: |
-        # Find the .so file generated by pybind11
-        if [ "${{ matrix.os }}" == 'macos-latest' ]; then
-          module_file=$(find gbrl/ -name "*.so")
-        elif [ "${{ matrix.os }}" == 'windows-latest' ]; then
-          module_file=$(find gbrl/ -name "*.pyd")
-        fi
+
+        module_file=$(find gbrl/ -name "*.so")
         if [ -z "$module_file" ]; then
             echo "Pybind11 module not found"
             exit 1
@@ -74,12 +72,23 @@ jobs:
         
         # Inspect the linked libraries
         otool -L $module_file
+    
+    - name: Check linked libraries Windows
+      if: matrix.os == 'windows-latest'
+      shell: powershell
+      run: |
+        $module_file = Get-ChildItem gbrl\ -Filter "*.pyd"
+        if ($null -eq $module_file) {
+          Write-Error "Pybind11 module not found"
+          exit 1
+        }
+        dumpbin /DEPENDENTS $module_file
     - name: Run tests without env variables
       continue-on-error: true
       run: |
-        if [ "${{ matrix.os }}" == 'macos-latest' ]; then
-          export DYLD_LIBRARY_PATH="${PWD}/gbrl/include/libomp"
-        fi
+        # if [ "${{ matrix.os }}" == 'macos-latest' ]; then
+        #   export DYLD_LIBRARY_PATH="${PWD}/gbrl/include/libomp"
+        # fi
         python -m unittest discover tests
 
 
