cheecking

diff --git a/.github/workflows/os_test.yml b/.github/workflows/os_test.yml
--- a/.github/workflows/os_test.yml
+++ b/.github/workflows/os_test.yml
@@ -51,7 +51,7 @@ jobs:
         export CC="/usr/bin/gcc"
         pip install . -v
         module_file=$(find gbrl/ -name "*.so")
-        install_name_tool -change /opt/homebrew/opt/libomp/lib/libomp.dylib @loader_path/../include/libomp/libomp.dylib $module_file
+        install_name_tool -change /opt/homebrew/opt/libomp/lib/libomp.dylib @loader_path/include/libomp/libomp.dylib $module_file
     
     - name: Install Python dependencies and build the project windows
       if: matrix.os == 'windows-latest'
@@ -73,16 +73,16 @@ jobs:
         # Inspect the linked libraries
         otool -L $module_file
     
-    - name: Check linked libraries Windows
-      if: matrix.os == 'windows-latest'
-      shell: powershell
-      run: |
-        $module_file = Get-ChildItem gbrl\ -Filter "*.pyd"
-        if ($null -eq $module_file) {
-          Write-Error "Pybind11 module not found"
-          exit 1
-        }
-        dumpbin /DEPENDENTS $module_file
+    # - name: Check linked libraries Windows
+    #   if: matrix.os == 'windows-latest'
+    #   shell: powershell
+    #   run: |
+    #     $module_file = Get-ChildItem gbrl\ -Filter "*.pyd"
+    #     if ($null -eq $module_file) {
+    #       Write-Error "Pybind11 module not found"
+    #       exit 1
+    #     }
+    #     dumpbin /DEPENDENTS $module_file
     - name: Run tests without env variables
       continue-on-error: true
       run: |
