debugging

diff --git a/.github/workflows/os_test.yml b/.github/workflows/os_test.yml
--- a/.github/workflows/os_test.yml
+++ b/.github/workflows/os_test.yml
@@ -52,6 +52,8 @@ jobs:
         python -m pip install --upgrade pip
         BREW_PREFIX=$(brew --prefix)
         LLVM_PREFIX=$(brew --prefix llvm)
+        export LIBOMP_PREFIX=$(brew --prefix libomp)
+        echo brew --prefix libomp
 
         export LDFLAGS="-L${BREW_PREFIX}/libomp/lib -L${LLVM_PREFIX}/lib -L${LLVM_PREFIX}/lib/c++ -Wl,-rpath,${LLVM_PREFIX}/lib/c++ -lunwind"
         export CPPFLAGS="-I${BREW_PREFIX}/libomp/include -I${LLVM_PREFIX}/include"
@@ -63,16 +65,19 @@ jobs:
 
     - name: Check linked libraries
       run: |
-        otool -L gbrl/gbrl_cpp.so
+        # Find the .so file generated by pybind11
+        module_file=$(find gbrl/ -name "*.so")
+        if [ -z "$module_file" ]; then
+            echo "Pybind11 module not found"
+            exit 1
+        fi
+        echo "Found module: $module_file"
+        
+        # Inspect the linked libraries
+        otool -L $module_file
 
     - name: Run tests
       run: |
-        export LDFLAGS="-L${BREW_PREFIX}/libomp/lib -L${LLVM_PREFIX}/lib -L${LLVM_PREFIX}/lib/c++ -Wl,-rpath,${LLVM_PREFIX}/lib/c++ -lunwind"
-        export CPPFLAGS="-I${BREW_PREFIX}/libomp/include -I${LLVM_PREFIX}/include"
-        export CC="$(brew --prefix llvm)/bin/clang"
-        export CXX="$(brew --prefix llvm)/bin/clang++"
-        export PATH="${LLVM_PREFIX}/bin:$PATH"
-        export DYLD_LIBRARY_PATH="${LLVM_PREFIX}/lib:${BREW_PREFIX}/libomp/lib:$DYLD_LIBRARY_PATH"
         # python -m unittest discover tests
         lldb -- python -m unittest discover tests
 
